### ISSUE TITLE
Issue when calling voice API via Gradio

### ISSUE THREAD

**Issue by RaspberryTech01** [ZillaRU/EmotiVoice-TPU#7]
When using the Radxa v0.1.2, I can load up gradio and access the web interface, but when it calls the voice API it has an issue

```shell
(.venv) admin@Airbox:/data/software/EmotiVoice-TPU$ bash run_gr.sh 
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 2.313 seconds.
Prefix dict has been built successfully.
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/bert_poolout1-768_1-512_1-512_1-512.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_bert
[tid=af9ab010] INFO:   Input 0) 'input_ids.1' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'attention_mask.1' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 2) 'token_type_ids.1' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '1060' shape=[ 1 768 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/jit_am_encoder_1-512-384_1-1-512.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_am_encoder
[tid=af9ab010] INFO:   Input 0) 'xs.1' shape=[ 1 512 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'masks.1' shape=[ 1 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '383_f32' shape=[ 1 512 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/onnx_am_decoder_1-2048-384.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_am_decoder
[tid=af9ab010] INFO:   Input 0) 'x' shape=[ 1 2048 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '399_LayerNormalization_f32' shape=[ 1 2048 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/am_durationpred-1_512_384-1_512_1.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_duration_pred
[tid=af9ab010] INFO:   Input 0) 'xs.2' shape=[ 1 512 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'x_masks.1' shape=[ 1 512 1 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '18_f32' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/am_pitchpred-1_512_384-1_512_1.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_pitch_pred
[tid=af9ab010] INFO:   Input 0) 'xs.2' shape=[ 1 512 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'x_masks.1' shape=[ 1 512 1 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '22_f32' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/am_energypred-1_512_384-1_512_1.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: emotivoice_energy_pred
[tid=af9ab010] INFO:   Input 0) 'xs.2' shape=[ 1 512 384 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'x_masks.1' shape=[ 1 512 1 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '19_f32' shape=[ 1 512 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/tts/hifigan_1-80-1024_F16.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: hifigan
[tid=af9ab010] INFO:   Input 0) 'input.1' shape=[ 1 80 1024 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '668_Tanh' shape=[ 1 1 262144 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO: USING DEVICES: 0 
[tid=af9ab010] INFO: init context on device 0
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./model_file/converter/decoder_2048_f16.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
[tid=af9ab010] INFO: NetName: openvoice_dec
[tid=af9ab010] INFO:   Input 0) 'input.1' shape=[ 1 192 2048 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Input 1) 'input.3' shape=[ 1 256 1 ] dtype=FLOAT32 scale=1
[tid=af9ab010] INFO:   Output 0) '664_Tanh' shape=[ 1 1 524288 ] dtype=FLOAT32 scale=1
Loaded checkpoint './model_file/converter'
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
  |     response_sent.set()
  |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     response_sent.set()
    |   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    |     self.gen.throw(type, value, traceback)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/gradio/route_utils.py", line 632, in dispatch
    |     response = await call_next(request)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 291, in app
    |     solved_result = await solve_dependencies(
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 658, in solve_dependencies
    |     ) = await request_body_to_args(  # body_params checked above
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 883, in request_body_to_args
    |     fields_to_extract = get_cached_model_fields(first_field.type_)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 658, in get_cached_model_fields
    |     return get_model_fields(model)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    |     return [
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    |     ModelField(field_info=field_info, name=name)
    |   File "<string>", line 6, in __init__
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 110, in __post_init__
    |     self._type_adapter: TypeAdapter[Any] = TypeAdapter(
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 257, in __init__
    |     self._init_core_attrs(rebuild_mocks=False)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    |     return func(self, *args, **kwargs)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    |     self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    |     schema = gen.generate_schema(type_)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    |     schema = self._generate_schema_inner(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    |     return self._annotated_schema(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    |     schema = self._apply_annotations(source_type, annotations)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    |     schema = get_inner_schema(source_type)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    |     schema = self._handler(source_type)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    |     schema = metadata_get_schema(source, get_inner_schema)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    |     lambda source, handler: handler(source)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    |     schema = self._handler(source_type)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    |     schema = self._generate_schema_inner(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    |     return self.match_type(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    |     return self._match_generic_type(obj, origin)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    |     return self._union_schema(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    |     choices.append(self.generate_schema(arg))
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    |     schema = self._generate_schema_inner(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    |     return self.match_type(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    |     return self._unknown_type_schema(obj)
    |   File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    |     raise PydanticSchemaGenerationError(
    | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
    | 
    | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
    | 
    | For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 189, in __call__
    response_sent.set()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/gradio/route_utils.py", line 632, in dispatch
    response = await call_next(request)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 658, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 883, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 658, in get_cached_model_fields
    return get_model_fields(model)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/data/software/EmotiVoice-TPU/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
``` 

How should this be fixed?

**Comment by ZillaRU** [comment]
This exception may be attributed to [the incompatibility issue with gradio](https://github.com/gradio-app/gradio/issues/9278). Please try `pip install gradio -U`.

**Comment by RaspberryTech01** [comment]
That seems to have fixed it.
